project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - posts/*.qmd
    - life/*.qmd
    - resume.qmd

website:
  title: "crrow"
  site-url: "https://crrow.github.io/crrow/"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: posts/index.qmd
        text: Posts
      - href: life/index.qmd
        text: Life
      - href: resume.qmd
        text: Resume

format:
  html:
    theme:
      light:
        - cosmo
        - styles-light.scss
      dark:
        - darkly
        - styles-dark.scss
    toc: true
