---
title: "About"
---

# Self Introduce

Hello, i'm deng huan, you can also call my ryan.

I'm a software engineer from China, i have four years of work experience in building and optimizing microservices, distribute systems using Go. And, I also have exposure to various areas, for example: cloud native(kubernetes), cloud services (aws), storage systems like file system, object storage system, and database. And also, i'm very interested in rust to build low level and high performance systems. Recently, i'm building a file store which aims to provide a extremely low latency write interface, so the caller can make response more quickly.

- Currently, i'm helping an AI bot company to upgrade its infrastructure to Kubernetes and optimizing the use AWS services, for example using IAM role properly to prevent security leak.

Looking back, i was a storage engineer at Megvii, it is an AI compute vision company, and they have a lot of data need to be store. I was responsible for enhancing the stability, throughput, and latency for their customized distributed storage services. Notably, i improve the average read latency and reduce the system usage by leveraging io-uring to reduce IO cost.

Moving forward, i'm eager to apply my knowledge to solve real-world challenges. I'm particularly interested in contributing to projects where I can leverage these skills to build scalable, reliable, and efficient solutions that can have a tangible impact.

# Why you leave ?

I'm looking for challenges and i also want to contribute to more meaningful projects.

- Megvii

Megvii is a big and mature platform, they have a whole AI training solution. But the financial report is not very good, and a bunch of researchers are leaving. So, after my leader's leaving, no one know what to do, since there are fewer people will use this system. Since its already a distributed system, managed by k8s, it can heal it self. Why would you spend so much time and heart on a old system that no-one is using? Thats the reason that i think i need to go out and seek for more challenges.

# Why you want to move to japan ?

I'm very interested in japan, I've visited Tokyo and Osaka three times in the last few months. I love how international the cities are; I can find amazing food from everywhere,

And as a software engineer, working in another country has always been a big dream of mine, and Japan is definitely at the top of that list. I'm really think Japan would have some great opportunities to grow and work on exciting projects.

So, for me, moving to Japan isn't just about living in a place I love; it's also a chance to take my career to the next level.

## Salary expectation ?

8M jpy

# Ask back

1. What's a typical day of this position?
2. How many people are on the cloud platform team right now?
    1. how many people do you plan to expand this team?
3. What do you like best about working for this company?
